spring:
  profiles:
    active: prod

elasticjob:
  tracing:
    type: RDB
  regCenter:
    serverLists: 10.255.209.99:3181
    namespace: elasticjob-lite-springboot
    connection-timeout-milliseconds: 30000
  jobs:
    simpleJob:
      elasticJobClass: com.example.springbootelasticjob.job.SpringBootSimpleJob
      cron: 0/5 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
    dataflowJob:
      elasticJobClass: com.example.springbootelasticjob.job.SpringBootDataflowJob
      cron: 0/5 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
    scriptJob:
      elasticJobType: SCRIPT
      cron: 0/10 * * * * ?
      shardingTotalCount: 3
      props:
        script.command.line: "echo SCRIPT Job: "
#    manualScriptJob:
#      elasticJobType: SCRIPT
#      jobBootstrapBeanName: manualScriptJobBean
#      shardingTotalCount: 9
#      props:
#        script.command.line: "echo Manual SCRIPT Job: "
    occurErrorNoticeWechatJob:
      elasticJobClass: com.example.springbootelasticjob.job.SpringBootOccurErrorNoticeWechatJob
      overwrite: true
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      jobErrorHandlerType: WECHAT
      jobBootstrapBeanName: occurErrorNoticeWechatBean
      props:
        wechat:
          webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=5606162a-e261-4d5a-8382-d2edd5dc9e56
          connectTimeout: 3000
          readTimeout: 5000
    occurErrorNoticeEmailJob:
      elasticJobClass: com.example.springbootelasticjob.job.SpringBootOccurErrorNoticeEmailJob
      overwrite: true
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      jobErrorHandlerType: EMAIL
      jobBootstrapBeanName: occurErrorNoticeEmailBean
      props:
        email:
          host: host
          port: 465
          username: username
          password: password
          useSsl: true
          subject: ElasticJob error message
          from: from@xxx.xx
          to: to1@xxx.xx,to2@xxx.xx
          cc: cc@xxx.xx
          bcc: bcc@xxx.xx
          debug: false
  dump:
    port: 9888